name: 🛠️ Refactor
description: Suggest code improvements or refactoring
title: "[Refactor] "
labels: refactor

body:
  - type: textarea
    id: problem
    attributes:
      label: Is your refactoring related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: refactoring
    attributes:
      label: Describe the refactoring you'd like
      description: A clear and concise description of what should be refactored.
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits of the refactoring
      description: Describe how this refactoring will improve the project.
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the refactoring here.
    validations:
      required: false