name: CI

env:
  GO_VERSION: "1.22.7"

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - .github/PULL_REQUEST_TEMPLATE.md
      - .github/CODEOWNERS.md
      - .github/workflows/release.yaml
      - .github/ISSUE_TEMPLATE/**
      - "docs/**"
      - "examples/**"
      - .editorconfig
      - .gitignore
      - LICENSE
      - README.md
      - mkdocs.yml
      - requirements.txt
      - Dockerfile.mkdocs

jobs:
  check_lint:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup GO Version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Lint
        run: make lint

  check_tests:
    name: Check Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup GO Version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Test
        run: make test

      - name: Race Test
        run: make test-race
